#!/usr/bin/env perl
use strict;
use warnings;
use Digest::MD5;

my $mysql_opt = "-h192.168.77.77 -uccadmin -pccpassword ccdb";
my $query = "select name,buildpacks.key from buildpacks order by position";
open(my $fh, "mysql $mysql_opt -e '$query' 2>/dev/null |") or die;

print "[";
while (<$fh>) {
    next if $. == 1;
    chomp;
    my($name,$key) = split /\t/;
    my $md5 = Digest::MD5::md5_hex($key);
    print "," if $. > 2;
    print qq({"name":"$name","path":"/tmp/buildpacks/$md5"});
}
print "]";
